### ISSUE TITLE
Studio theme colors are not cohesive on list item hover

### ISSUE THREAD

**Issue by ndimatteo** [sanity-io/orderable-document-list#60]
When hovering over a list item, the studio theme styles are applied but there appears to be a background color applied behind the title + subtitle in the list item (for both light/dark mode):

<img width="393" alt="image" src="https://user-images.githubusercontent.com/737188/228652343-a12a3966-f41b-4d5d-ae10-611e2891e232.png">

<img width="400" alt="image" src="https://user-images.githubusercontent.com/737188/228652423-e0175ea5-7ff3-42f0-b85c-3477a718ca75.png">

**Comment by martinkz** [comment]
I have the same issue and had to create a global css style to override those. This is what I put in it in order to make the orderable Document list look like the regular Document lists:

`#box-orderable-box-0 {
  max-width: 350px;
}
#box-orderable-box-0 [data-ui='Card'] {
  background-color: transparent;
}
`

You can import the custom css file in your sanity.config.js:

`import './customOverrides.css'`

**Comment by sn4h** [comment]
This probably breaks something but with the same procedure as @martinkz:
`
[data-ui='Card'],
[data-ui='Flex'] {
    background-color: transparent !important;
}
`

**Comment by maxstoyanov** [comment]
Confirmed. The bug appears on the light and dark default theme.
(Using version 1.0.4 with studio 3.12.2)
